### PR TITLE
Feature/20180307/update evernote sdk

### PR DESCRIPTION
**Pull request by pplgin**
- update evernote sdk
- remove noteStoreUrl config

### CODE REVIEW

**Comment by pplgin** [comment]
https://github.com/evernote/evernote-sdk-python/blob/master/sample/client/EDAMTest.py @bordaigorl

**Comment by bordaigorl** [comment]
Hi @pplgin thanks for your interest in the plugin.
Have you tested this on ST3?
The python sdk by default only supports python2, the sdk for python3 is at a different repo:
https://github.com/evernote/evernote-sdk-python3

**Comment by pplgin** [comment]
I have already tested, you can use my branch code directly

**Comment by pplgin** [comment]
Hi @bordaigorl , have you tested my branch?

**Comment by bordaigorl** [comment]
Hi @pplgin I haven't tested it yet (just very busy) I plan to do that during the weekend.
Thank you for your contribution!

**Pull request closed without merging**
