### PR TITLE
Add content wrapper for all markdown

### PR DESCRIPTION
**Pull request by ranmocy**
I'm seeking a way to add a global wrapper to users' notes. By this way, it is possible to set font, color, etc for the entire note.

### CODE REVIEW

**Comment by bordaigorl** [comment]
I think this is a good idea.

1. Before merging I would remove the opinionated default and let the user set `body_wrapper` if they want to customise it.
2. Also I would probably call the setting simply `body`, the user does not need to know it's actually a wrapper div and may find `wrapper` confusing.
3. Test it thoroughly:
  - What happens when you view the note with other clients (desktop or webapp)?
  - What happens when you edit the note with other clients? Is the wrapper respected, stripped, ignored?
  - What happens when you re-open in the plugin a note that has been edited with another client? I.e. do we need to make the html2markdown library aware of the wrapper?

If it is not in conflict with other client's assumptions, I think this is a nice solution to the problem of customising normal paragraphs.
Thanks for the contribution!

**Comment by ranmocy** [comment]
Modified name and default settings.

1. View the note with other clients looks fine.
2. When edit with other clients, normal edit will be fine. But if user try to empty the note, the last delete action will remove the wrapper.
3. Now the main problem I missed is that if the wrapper exists and user reopen it in the plugin, the user will see that `div` in the note. So I guess the wrapper needs to be hidden when user reopen it, either by remove it before html2text, or after it.

**Comment by ranmocy** [comment]
Do you have any idea to detect this unique wrapper? What if user already have some `div` wrapper?

**Comment by ranmocy** [comment]
The third one I talked about is not very precise.
It only happens if user edits the note on another client, which will remove plugin's hidden comment.

**Comment by bordaigorl** [comment]
@ranmocy it is actually possible (and less problematic) to attach a `style` attribute to the `<en-note>` tag directly. The webapp parses it correctly, I do not know about the other clients.
When you edit the note in other clients the attribute is removed and the global style reverted to default, but this does not affect the content, nor the markdown. When you then re-open the note from the plugin and save again, the style is re-insterted. Would this be acceptable?

**Comment by ranmocy** [comment]
@bordaigorl It is a good idea to attach the style to `en-node` tag, and I did so.
I tested web client and Mac client. Both of them parse correctly.
When user edit in web client, the style is removed. But not in Mac client, which is reserved.
I think it's good enough now. What you think?

**Comment by bordaigorl** [comment]
It looks good!
Thanks for the contribution.
I'll review the code soon in view of the next release.

**Comment by ranmocy** [comment]
Just a little ping for reminding.

**Comment by bordaigorl** [comment]
Hi @ranmocy thanks for the reminder.
I am currently very busy but this will be eventually merged in the new version.
I plan to give the plugin some love in a month or so...stay tuned!

**Comment by ranmocy** [comment]
Looking forward to it!

**Pull request merged**
